<?php
namespace Tests\Feature;
use App\Jobs\IssueInvoice;
use App\Models\ArcaProfile;
use App\Models\BillingAccessToken;
use App\Models\BillingClient;
use App\Models\Invoice;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Bus;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;
class BillingApiTest extends TestCase
{
 use RefreshDatabase;
 private function profile(string $slug='rocca'):ArcaProfile{return ArcaProfile::create(['slug'=>$slug,'name'=>$slug,'cuit'=>'20123456789','sales_point'=>1,'business_name'=>'Rocca','address'=>'Bariloche','vat_condition'=>'RI','certificate_path'=>'x.crt','private_key_path'=>'x.key','ta_path'=>'TA.xml']);}
 private function client(string $slug,ArcaProfile $p, string $password='secret-password'):BillingClient{return BillingClient::create(['slug'=>$slug,'name'=>$slug,'username'=>$slug,'password_hash'=>Hash::make($password),'default_arca_profile_id'=>$p->id]);}
 private function login(string $username,string $password='secret-password'):string{return $this->postJson('/api/v1/auth/login',compact('username','password'))->assertOk()->json('data.token');}
 private function payload(array $changes=[]):array{return array_replace_recursive(['external_reference'=>'REF-1','invoice_type'=>'B','customer'=>['name'=>'Ana','address'=>'Bariloche','vat_condition'=>'Consumidor Final','document_type'=>99,'document_number'=>0],'items'=>[['description'=>'Servicio','quantity'=>2,'unit_price'=>100]],'total'=>200,'email_to'=>'ana@example.test'],$changes);}
 private function post(string $token,string $key,array $payload=[]){return $this->withToken($token)->withHeader('Idempotency-Key',$key)->postJson('/api/v1/invoices',$payload?:$this->payload());}
 public function test_both_clients_can_login_and_secrets_are_hashed():void{$p=$this->profile();foreach(['reservas','comandas'] as $s){$c=$this->client($s,$p);$token=$this->login($s);$this->assertFalse(Hash::needsRehash($c->password_hash));$this->assertNotSame('secret-password',$c->password_hash);$this->assertDatabaseHas('billing_access_tokens',['token_hash'=>hash('sha256',$token)]);$this->assertDatabaseMissing('billing_access_tokens',['token_hash'=>$token]);}}
 public function test_bad_login_cases_are_unauthorized():void{$p=$this->profile();$c=$this->client('reservas',$p);$this->postJson('/api/v1/auth/login',['username'=>'missing','password'=>'x'])->assertUnauthorized();$this->postJson('/api/v1/auth/login',['username'=>'reservas','password'=>'wrong'])->assertUnauthorized();$c->update(['active'=>false]);$this->postJson('/api/v1/auth/login',['username'=>'reservas','password'=>'secret-password'])->assertUnauthorized();}
 public function test_invalid_missing_and_expired_tokens():void{$this->getJson('/api/v1/invoices/x')->assertUnauthorized()->assertJsonPath('message','Token inválido.');$this->withToken('bad')->getJson('/api/v1/invoices/x')->assertUnauthorized();$p=$this->profile();$c=$this->client('reservas',$p);$plain='expired';BillingAccessToken::create(['billing_client_id'=>$c->id,'token_hash'=>hash('sha256',$plain),'expires_at'=>now()->subMinute()]);$this->withToken($plain)->getJson('/api/v1/invoices/x')->assertUnauthorized()->assertJsonPath('data.token_expired',true);}
 public function test_clients_create_owned_invoices_with_default_profile_and_source():void{Bus::fake();$p=$this->profile();foreach(['reservas','comandas'] as $s){$c=$this->client($s,$p);$r=$this->post($this->login($s),"same-key",$this->payload(['external_reference'=>$s]))->assertAccepted()->assertJsonPath('source',$s);$this->assertDatabaseHas('invoices',['id'=>$r->json('id'),'billing_client_id'=>$c->id,'arca_profile_id'=>$p->id]);}Bus::assertDispatchedTimes(IssueInvoice::class,2);}
 public function test_profile_is_restricted_to_configured_default():void{$p=$this->profile();$this->profile('other');$this->client('reservas',$p);$this->post($this->login('reservas'),'k',$this->payload(['profile'=>'other']))->assertUnprocessable()->assertSee('no está permitido');}
 public function test_idempotency_replays_same_payload_and_rejects_different_payload():void{Bus::fake();$p=$this->profile();$this->client('reservas',$p);$t=$this->login('reservas');$first=$this->post($t,'payment-1')->assertAccepted();$this->post($t,'payment-1')->assertOk()->assertJsonPath('id',$first->json('id'));$this->post($t,'payment-1',$this->payload(['total'=>201]))->assertUnprocessable();$changed=$this->payload(['external_reference'=>'OTHER']);$this->post($t,'payment-1',$changed)->assertStatus(409);$this->assertDatabaseCount('invoices',1);Bus::assertDispatchedTimes(IssueInvoice::class,1);}
 public function test_retry_after_expiry_does_not_duplicate():void{Bus::fake();$p=$this->profile();$c=$this->client('reservas',$p);$t=$this->login('reservas');$id=$this->post($t,'retry')->assertAccepted()->json('id');BillingAccessToken::where('billing_client_id',$c->id)->update(['expires_at'=>now()->subSecond()]);$this->post($t,'retry')->assertUnauthorized()->assertJsonPath('data.token_expired',true);$this->post($this->login('reservas'),'retry')->assertOk()->assertJsonPath('id',$id);$this->assertDatabaseCount('invoices',1);}
 public function test_database_unique_constraint_is_the_concurrency_guard():void{$p=$this->profile();$c=$this->client('reservas',$p);$row=['billing_client_id'=>$c->id,'idempotency_key'=>'race','request_fingerprint'=>'same','arca_profile_id'=>$p->id,'external_reference'=>'R','status'=>'pending','invoice_type'=>'B','request_payload'=>$this->payload()];Invoice::create($row);$this->expectException(\Illuminate\Database\QueryException::class);Invoice::create($row);}
 public function test_invoice_and_pdf_are_isolated():void{Storage::fake();$p=$this->profile();$a=$this->client('reservas',$p);$this->client('comandas',$p);$invoice=Invoice::create(['billing_client_id'=>$a->id,'idempotency_key'=>'k','request_fingerprint'=>'f','arca_profile_id'=>$p->id,'external_reference'=>'R','status'=>'completed','invoice_type'=>'B','request_payload'=>$this->payload(),'pdf_path'=>'invoices/a.pdf']);Storage::put('invoices/a.pdf','pdf');$token=$this->login('comandas');$this->withToken($token)->getJson('/api/v1/invoices/'.$invoice->id)->assertNotFound();$this->withToken($token)->get('/api/v1/invoices/'.$invoice->id.'/pdf')->assertNotFound();}
 public function test_validation_of_header_payload_and_total():void{$p=$this->profile();$this->client('reservas',$p);$t=$this->login('reservas');$this->withToken($t)->postJson('/api/v1/invoices',$this->payload())->assertUnprocessable();$this->post($t,'x',[])->assertUnprocessable();$this->post($t,'x',$this->payload(['total'=>999]))->assertUnprocessable();}
}
