<?php
namespace Tests\Feature;
use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Http\UploadedFile; use Illuminate\Support\Facades\Storage; use Tests\TestCase;
class SettingsProfileTest extends TestCase { use RefreshDatabase;
 private function credentials():array{$key=openssl_pkey_new(['private_key_bits'=>2048]);$csr=openssl_csr_new(['commonName'=>'test.example'],$key);$cert=openssl_csr_sign($csr,null,$key,1);openssl_x509_export($cert,$certText);openssl_pkey_export($key,$keyText);return [UploadedFile::fake()->createWithContent('test.crt',$certText),UploadedFile::fake()->createWithContent('test.key',$keyText)];}
 private function data():array{[$c,$k]=$this->credentials();return ['name'=>'Rocca','cuit'=>'20123456789','sales_point'=>2,'business_name'=>'Refugio','address'=>'Bariloche','vat_condition'=>'RI','certificate'=>$c,'private_key'=>$k];}
 public function test_valid_profile_is_stored_and_can_be_edited():void{Storage::fake();$this->withSession(['settings_authenticated'=>true])->post('/settings/profiles',$this->data())->assertSessionHasNoErrors();$p=\App\Models\ArcaProfile::firstOrFail();$this->assertSame('20123456789',$p->cuit);$this->withSession(['settings_authenticated'=>true])->put('/settings/profiles/'.$p->id,['name'=>'Rocca 2','cuit'=>'20123456789','sales_point'=>3,'business_name'=>'Refugio','address'=>'Bariloche','vat_condition'=>'RI'])->assertSessionHasNoErrors();$this->assertSame(3,$p->fresh()->sales_point);}
 public function test_invalid_fiscal_data_is_rejected():void{$d=$this->data();$d['cuit']='123';$d['sales_point']=0;$this->withSession(['settings_authenticated'=>true])->post('/settings/profiles',$d)->assertSessionHasErrors(['cuit','sales_point']);}
 public function test_invalid_or_mismatched_credentials_are_rejected():void{$d=$this->data();$d['certificate']=UploadedFile::fake()->createWithContent('bad.crt','bad');$this->withSession(['settings_authenticated'=>true])->post('/settings/profiles',$d)->assertSessionHasErrors('certificate');[$otherCert]=$this->credentials();$d=$this->data();$d['certificate']=$otherCert;$this->withSession(['settings_authenticated'=>true])->post('/settings/profiles',$d)->assertSessionHasErrors('private_key');}
}
