[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/run/supervisord.pid

[program:php-fpm]
command=php-fpm --nodaemonize
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
autorestart=true
priority=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:queue]
command=php /var/www/app/artisan queue:work --sleep=3 --tries=5 --timeout=120 --max-time=3600
user=www-data
autorestart=true
stopasgroup=true
killasgroup=true
priority=30
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:scheduler]
command=php /var/www/app/artisan schedule:work
user=www-data
autorestart=true
stopasgroup=true
killasgroup=true
priority=30
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

