@extends('layouts.settings')
@section('title','Administración')
@section('styles')
.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.section{margin-top:2rem}.form-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:.8rem}.wide{grid-column:1/-1}.cards{display:grid;gap:1rem}.card{padding:1rem}.meta{color:var(--muted);font-size:.85rem}.terminal{max-height:360px;overflow:auto;padding:1rem;color:#c9f7d4;background:#101714;border-radius:5px;font:13px/1.6 ui-monospace,SFMono-Regular,monospace}.terminal-line{border-bottom:1px solid #243129;padding:.25rem 0}.terminal time{color:#8ca897}.terminal .warn{color:#ffd479}.table-wrap{overflow:auto}.trace{width:100%;border-collapse:collapse;font-size:.82rem}.trace th,.trace td{padding:.6rem;border-bottom:1px solid var(--line);text-align:left;white-space:nowrap}.countdown{font:1.5rem ui-monospace,monospace;color:var(--brand-dark)}@media(max-width:800px){.grid,.form-grid{grid-template-columns:1fr}}
@endsection
@section('header-action')<form method="post" action="{{route('settings.logout')}}">@csrf<button class="header-action">Cerrar sesión</button></form>@endsection
@section('content')
<main class="page"><h1 class="page-title">Facturación central</h1><p class="page-intro">Puntos de venta ARCA, trazabilidad y estado del cronómetro.</p>
@if(session('status'))<div class="alert alert--success">{{session('status')}}</div>@endif
@if($errors->any())<div class="alert alert--danger"><strong>No se pudieron guardar los datos.</strong><ul>@foreach($errors->all() as $e)<li>{{$e}}</li>@endforeach</ul></div>@endif
<section class="panel section"><div class="panel__header"><h2>Registrar punto de venta</h2><p>Los archivos se validan con OpenSSL y se guardan en storage privado.</p></div><form method="post" enctype="multipart/form-data" action="{{route('settings.profiles.store')}}">@csrf<div class="panel__body form-grid">
@foreach(['name'=>'Nombre','cuit'=>'CUIT (11 dígitos)','sales_point'=>'Punto de venta','business_name'=>'Razón social','address'=>'Domicilio','vat_condition'=>'Condición IVA','gross_income'=>'Ingresos brutos','activity_started_at'=>'Inicio de actividades'] as $key=>$label)<label class="field"><span>{{$label}}</span><input name="{{$key}}" value="{{old($key)}}" @if(!in_array($key,['gross_income','activity_started_at'])) required @endif></label>@endforeach
<label class="field"><span>Certificado (.crt)</span><input type="file" name="certificate" accept=".crt" required></label><label class="field"><span>Private key (.key)</span><input type="file" name="private_key" accept=".key" required></label><button class="button-primary" type="submit">Registrar</button></div></form></section>
<section class="section"><h2>Puntos de Venta</h2><div class="cards">@forelse($profiles as $profile)<article class="panel card"><div class="grid"><div><h3>{{$profile->name}}</h3><p class="meta">{{$profile->slug}} · CUIT {{$profile->cuit}} · PV {{$profile->sales_point}}</p><p>Próxima renovación del TA: <span class="countdown" data-next-renewal="{{$profile->next_renewal_at?->toIso8601String()}}">--:--:--</span></p><small>{{$profile->last_renewal_at ? 'Última renovación '.$profile->last_renewal_at->diffForHumans() : 'Pendiente de primera renovación'}}</small></div><form method="post" enctype="multipart/form-data" action="{{route('settings.profiles.update',$profile)}}">@csrf @method('PUT')<div class="form-grid">
@foreach(['name','cuit','sales_point','business_name','address','vat_condition','gross_income','activity_started_at'] as $key)<label class="field"><span>{{str_replace('_',' ',ucfirst($key))}}</span><input name="{{$key}}" value="{{$key==='activity_started_at' ? $profile->$key?->format('Y-m-d') : $profile->$key}}" @if(!in_array($key,['gross_income','activity_started_at'])) required @endif></label>@endforeach
<label class="field"><span>Nuevo .crt (opcional)</span><input type="file" name="certificate" accept=".crt"></label><label class="field"><span>Nueva .key (opcional)</span><input type="file" name="private_key" accept=".key"></label><button class="button-primary">Guardar cambios</button></div></form></div></article>@empty<p>No hay perfiles.</p>@endforelse</div></section>
<section class="panel section"><div class="panel__header"><h2>Cómo funciona el cronometrado</h2></div><div class="panel__body"><p>El scheduler de Laravel se mantiene activo dentro del contenedor y dispara <code>arca:renew-tickets</code> cada seis horas. Cada tarjeta calcula localmente la cuenta regresiva desde la última renovación; además, ARCA renueva bajo demanda si al ticket le quedan menos de {{config('billing.arca.renew_before_minutes')}} minutos. Las activaciones y renovaciones quedan registradas abajo.</p></div></section>
<section class="section"><h2>Historial del sistema</h2><div class="terminal" role="log">@forelse($history as $event)<div class="terminal-line"><time>[{{$event->created_at?->timezone(config('app.timezone'))->format('Y-m-d H:i:s')}}]</time> <span class="{{$event->level}}">{{$event->event}}</span> — {{$event->message}} @if($event->context)<span>{{json_encode($event->context,JSON_UNESCAPED_UNICODE)}}</span>@endif</div>@empty> Sin eventos todavía.@endforelse</div></section>
<section class="panel section"><div class="panel__header"><h2>Trazabilidad de facturas</h2></div><div class="table-wrap"><table class="trace"><thead><tr><th>Recibida</th><th>Cliente</th><th>Referencia</th><th>Idempotencia</th><th>Fingerprint</th><th>Estado</th><th>Perfil / PV</th><th>Comprobante</th><th>CAE / Vto.</th><th>Email</th><th>Error</th></tr></thead><tbody>@foreach($invoices as $i)<tr><td>{{$i->created_at}}</td><td>{{$i->billingClient?->slug??'legacy'}}</td><td>{{$i->external_reference}}</td><td>{{$i->idempotency_key}}</td><td title="{{$i->request_fingerprint}}">{{Str::limit($i->request_fingerprint,12)}}</td><td>{{$i->status}}</td><td>{{$i->profile?->slug}} / {{$i->profile?->sales_point}}</td><td>{{$i->voucher_number??'-'}}</td><td>{{$i->cae??'-'}} / {{$i->cae_expires_at?->format('Y-m-d')??'-'}}</td><td>{{$i->emailed_at??'-'}}</td><td>{{Str::limit($i->error,80)}}</td></tr>@endforeach</tbody></table></div></section>
</main>@endsection
@section('scripts')<script>const clocks=document.querySelectorAll('[data-next-renewal]');function tick(){clocks.forEach(c=>{const t=Date.parse(c.dataset.nextRenewal),d=Math.max(0,t-Date.now());if(!t){c.textContent='Pendiente';return}if(!d){c.textContent='Renovando…';return}c.textContent=[Math.floor(d/3600000),Math.floor(d%3600000/60000),Math.floor(d%60000/1000)].map(v=>String(v).padStart(2,'0')).join(':')})}tick();setInterval(tick,1000)</script>@endsection
